server:
  port: 7001

eureka:
  instance:
    hostname: eureka-server01.com
    prefer-ip-address: false
    instance-id: server01-7001
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server02.com:7002/eureka/

spring:
  application:
    name: server
  #springboot-admin
  boot:
    admin:
      client:
        url: http://admin8899.com:8899

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always
