server:
  port: 8001

spring:
  application:
    name: provider
  zipkin:
    base-url: http://127.0.0.1:9411/
  sleuth:
    sampler:
      rate: 1
  boot:
    admin:
      client:
        url: http://admin8899.com:8899
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server01.com:7001/eureka/,http://eureka-server02.com:7002/eureka/
  instance:
    instance-id: provider-8001
    hostname: provider8001.com

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always

logging:
  config: classpath:logback.xml
xxl:
  job:
    accessToken: ''
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      address: ''
      appname: provider-job
      ip: ''
      logpath: ./applogs/xxl-job/jobhandler
      logretentiondays: 30
      port: 1000
